// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vawzopphzdraikcirqrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhd3pvcHBoemRyYWlrY2lycXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjcwODQsImV4cCI6MjA1OTEwMzA4NH0.i3EM6njYz8aiI5Zz-TSXXfsvY5a15Ksx7mpwCY-F3sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);